remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [QUASI]
description: [QML for CFD simulations]

# Add custom CSS
style: |
  body {
    font-size: 24px;
  }
  h1 {
    font-size: 2.8em;
  }
  h2 {
    font-size: 2.2em;
  }
  h3 {
    font-size: 1.8em;
  }
  .navigation {
    background-color: #f5f5f5;
    padding: 10px 0;
    text-align: center;
    margin-bottom: 20px;
  }
  .navigation nav a {
    margin: 0 15px;
    color: #2879d0;
    text-decoration: none;
    font-weight: bold;
    font-size: 1.2em;
  }
  .navigation nav a:hover {
    text-decoration: underline;
  }
  .navigation nav a.active {
    color: #333;
  }